baseURL: "https://radiquum.wah.su"
languageCode: "en-us"
title: "Radiquum Blog"
theme: "stack"
DefaultContentLanguage: "en"
hasCJKLanguage: false

menu:
  social:
    - identifier: github
      name: GitHub
      url: https://github.com/radiquum
      weight: -200
      params:
        icon: brand-github
        newTab: true
    - identifier: bluesky
      name: BlueSky
      url: https://bsky.app/profile/radiquum.wah.su
      weight: -200
      params:
        icon: brand-bluesky
        newTab: true
    - identifier: mastodon
      name: Mastodon
      url: https://furry.engineer/@radiquum
      weight: -200
      params:
        icon: brand-mastodon
        newTab: true
    - identifier: bento
      name: bento
      url: https://bento.me/radiquum
      weight: -200
      params:
        icon: brand-bento
        newTab: true

permalinks:
  post: /p/:slug/
  page: /:slug/

params:
  favicon: /favicon.ico
  mainSections:
        - post
  featuredImageField: image
  rssFullContent: true
  sidebar:
        emoji: 🍎
        subtitle: Furry, Photographer, Coder and Self-Hosting Enthusiast.
  article:
        math: false
        toc: true
        readingTime: true
        license:
            enabled: true
            default: Licensed under CC BY-NC-SA 4.0
  widgets:
    homepage:
      - type: search
      - type: archives
        params:
          limit: 5
      - type: categories
        params:
          limit: 10
      - type: tag-cloud
        params:
          limit: 10
    page:
      - type: toc
