baseURL: "https://radiquum.wah.su/blog"
languageCode: "en-us"
title: "Radiquum Blog"
theme: "stack"

DefaultContentLanguage: "en"
hasCJKLanguage: false
languages:
    en:
        languageName: English
        title: Radiquum Blog
        weight: 1
    ru:
        languageName: Русский
        title: Radiquum Blog
        weight: 2

menu:
  social:
    - identifier: github
      name: GitHub
      url: https://github.com/radiquum
      weight: -200
      params:
        icon: brand-github
        newTab: true
    - identifier: bluesky
      name: BlueSky
      url: https://bsky.app/profile/radiquum.wah.su
      weight: -200
      params:
        icon: brand-bluesky
        newTab: true
    - identifier: mastodon
      name: Mastodon
      url: https://furry.engineer/@radiquum
      weight: -200
      params:
        icon: brand-mastodon
        newTab: true
    - identifier: links
      name: "About me"
      url: https://wah.su/radiquum
      weight: -200
      params:
        icon: material-symbols--light-link
        newTab: true

permalinks:
  post: /post/:slug/
  page: /:slug/

params:
  favicon: /favicon.ico
  defaultImage:
    opengraph:
      enabled: true
      local: true
      src: "img/opengraph_default.png"
  imageProcessing:
      cover:
          enabled: true
      content:
          enabled: true
  mainSections:
        - post
  featuredImageField: image
  rssFullContent: true
  sidebar:
        emoji: 🍎
        subtitle: Furry, Photographer, Coder and Self-Hosting Enthusiast.
  article:
        math: false
        toc: true
        readingTime: true
        license:
            enabled: true
            default: Licensed under CC BY-NC-SA 4.0
  widgets:
    homepage:
      - type: search
      - type: archives
        params:
          limit: 5
      - type: categories
        params:
          limit: 10
      - type: tag-cloud
        params:
          limit: 10
    page:
      - type: toc
  comments:
    enabled: true
    provider: giscus
    giscus:
      repo: "radiquum/blog"
      repoID: "R_kgDOLcLtlA"
      category: "Announcements"
      categoryID: "DIC_kwDOLcLtlM4Cdw10"
      mapping: "title"
      lightTheme: "light"
      darkTheme: "dark_dimmed"
      reactionsEnabled: 1
      emitMetadata: 0

enableRobotsTXT: true